run:
  tests: false

linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - varcheck

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000