run:
  tests: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - errcheck
    - exportloopref
    - goconst
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - testpackage
    - typecheck
    - unconvert
    - whitespace

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000