run:
  tests: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - goconst
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - paralleltest
    - promlinter
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - whitespace

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000