name: Build Novachain

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

# This workflow makes x86_64 binaries for mac, windows, and linux.
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        include:
          - targetos: darwin
            arch: arm64
    name: novachain ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile novachain
        run: |
          go mod download
          make install
