name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: a41ventures/carina
          tags: |
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    # if: "startsWith(github.event.head_commit.message, 'feat:')"

#  update_helm:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - run: |
#          mkdir -p output
#          echo "my env logging" > output/log
#          echo ${{ needs.build.outputs.tags }} >> output/log
#
#      - name: Check docker img tag value
#        uses: actions/upload-artifact@v3
#        with:
#          name: log-artifact
#          path: output/**/*
#
#      - name: Update helm img tag
#        uses: Carina-labs/tag-changer@main
#        with:
#          A41_PAT: ${{ secrets.A41_PAT }}
#          TAGS: ${{ needs.build.outputs.tags }}
