name: create release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout code
          uses: actions/checkout@v3.1.0
      -   name: set tag env
          run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -   name: install go
          uses: actions/setup-go@v3
          with:
            go-version: '1.18'
            check-latest: true
      -   name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
      -   name: Upload linux-amd64 artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./artifacts/gaiad-${{ env.VERSION }}-linux-amd64
            asset_name: gaiad-${{ env.VERSION }}-linux-amd64
            asset_content_type: application/binary
      -   name: Upload linux-arm64 artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./artifacts/gaiad-${{ env.VERSION }}-linux-arm64
            asset_name: gaiad-${{ env.VERSION }}-linux-arm64
            asset_content_type: application/binary